// for now i'll just shove a hard-coded map in here
import { TileType } from '../Tile/Tile'

// here's an attempt at hardcoding the original pacman map! 
    //hopefully it works :)
const HardcodedMap = [
    [TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP],
    [TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP],
    [TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP],
    [TileType.BOUNDARY_OUTCORNER, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_BUMP, TileType.BOUNDARY_BUMP, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_OUTCORNER],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_EDGE, TileType.OFFMAP, TileType.OFFMAP, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_EDGE, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_EDGE, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_EDGE, TileType.OFFMAP, TileType.OFFMAP, TileType.INNER_EDGE, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_OUTCORNER, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_INCORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.OPEN, TileType.BOUNDARY_INCORNER, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_OUTCORNER],
    [TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.OPEN, TileType.BOUNDARY_EDGE, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP],
    [TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.BOUNDARY_EDGE, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP],
    [TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.GB_CORNER, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.GB_DOOR, TileType.GB_DOOR, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.GB_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.BOUNDARY_EDGE, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP],
    [TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_INCORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.BOUNDARY_EDGE, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.BOUNDARY_INCORNER, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE],
    [TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.BOUNDARY_EDGE, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN],
    [TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_INCORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.BOUNDARY_EDGE, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.BOUNDARY_INCORNER, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE],
    [TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.GB_CORNER, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.GB_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.BOUNDARY_EDGE, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP],
    [TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.BOUNDARY_EDGE, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP],
    [TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.BOUNDARY_EDGE, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP],
    [TileType.BOUNDARY_OUTCORNER, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_INCORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.BOUNDARY_INCORNER, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_OUTCORNER],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_BUMP, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.BOUNDARY_BUMP],
    [TileType.BOUNDARY_BUMP, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.BOUNDARY_BUMP],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_CORNER, TileType.OPEN, TileType.INNER_CORNER, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_EDGE, TileType.INNER_CORNER, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_EDGE, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.OPEN, TileType.BOUNDARY_EDGE],
    [TileType.BOUNDARY_OUTCORNER, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_EDGE, TileType.BOUNDARY_OUTCORNER],
    [TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP],
    [TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP, TileType.OFFMAP],
]

export default HardcodedMap